### ISSUE TITLE
`job_transition` error in year 2021 iteration 

### ISSUE THREAD

**Issue by tianxie1995** [SEMCOG/semcog_urbansim#36]
Error message: 
```
Traceback (most recent call last):
  File "/home/da/semcog_urbansim/models.py", line 549, in jobs_transition
    new, added_jobs_idx, _ = model.transition(j, iter_var)
  File "/home/da/anaconda3/lib/python3.9/site-packages/urbansim/models/transition.py", line 517, in transition
    updated, added, copied, removed = self.transitioner(data, year)
  File "/home/da/anaconda3/lib/python3.9/site-packages/urbansim/models/transition.py", line 342, in __call__
    return self.transition(data, year)
  File "/home/da/anaconda3/lib/python3.9/site-packages/urbansim/models/transition.py", line 421, in transition
    return super(TabularTotalsTransition, self).transition(data, year)
  File "/home/da/anaconda3/lib/python3.9/site-packages/urbansim/models/transition.py", line 329, in transition
    updated = pd.concat(segments)
  File "/home/da/anaconda3/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/da/anaconda3/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 294, in concat
    op = _Concatenator(
  File "/home/da/anaconda3/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 351, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
```

**Comment by tianxie1995** [comment]
Bug cause: `large_area_id` in the buildings table while running `jobs_transition` are all `NaN`, this causing filter fails

**Comment by tianxie1995** [comment]
Fixed
